import "./modules/accordion";
import "./modules/close-alert";
import "./modules/close-global-banner";
import "./modules/copy-btn";
import "./modules/design-system-website-mobile-menu";
import "./modules/dialogs";
import "./modules/input-password.js"
import "./modules/menu";
import "./modules/navbar-components";
import "./modules/popper-popover";
import "./modules/popper-tooltip";
import "./modules/tabs";